### ISSUE TITLE
Data service needs some sort of ACL's

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/conductor.js#59]

**Comment by tarcieri** [comment]
There's a great alternative to ACLs or other identity-based access control systems: [capability-based security](https://en.wikipedia.org/wiki/Capability-based_security)

In a capability model, access is controlled by tokens that are necessary and sufficient in and of themselves in order to grant access to a particular resource.

I have plans to use Oasis/Conductor as part of a more wide-ranging capability-based security system, FYI. I'd like to expose a tokenization service for managing access to secrets in the outer page, providing tokens which map to actual secrets to Cards, then Cards can take action by providing the outer page with a token of interest and what action they'd like taken on it:

http://cryptosphere.org

**Comment by stefanpenner** [comment]
@tarcieri absolutely.

I am excited that you commented. Let me digest http://cryptosphere.org/
